title = "Mosaic Preferences"

[view_options]
window_size = 0

[media_library]
media_library_path = ""
show_on_start = false

[playlist]
show_on_start = false

[dock]
position = 'right'

[playback]
cover_art = true